// app/layout.tsx
import "./globals.css";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { cn } from "@/lib/utils";
import { dark } from "@clerk/themes";

// const inter = Inter({ subsets: ["latin"] , variable: "--font-inter")};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        variables: {
          colorPrimary: "#f97316",
          colorBackground: "#1f2937",
        },
      }}
    >
      <html className="h-full" lang="en">
        <body
          className={cn(
            inter.variable,
            "scroll-smooth h-full font-sans antialiased"
          )}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
